//
// Created by Alexander Taepper on 29.09.22.
//

#include "silo/query_engine.h"

std::string test = "{\n"
                   "    \"type\": \"And\",\n"
                   "    \"children\": [\n"
                   "      {\n"
                   "        \"type\": \"StrEq\",\n"
                   "        \"column\": \"country\",\n"
                   "        \"value\": \"Switzerland\"\n"
                   "      },\n"
                   "      {\n"
                   "        \"type\": \"DateBetw\",\n"
                   "        \"from\": \"2022-01-01\",\n"
                   "        \"to\": null\n"
                   "      },\n"
                   "      {\n"
                   "        \"type\": \"Or\",\n"
                   "        \"children\": [\n"
                   "          {\n"
                   "            \"type\": \"NucEq\",\n"
                   "            \"position\": 25407,\n"
                   "            \"value\": \"A\"\n"
                   "          },\n"
                   "          {\n"
                   "            \"type\": \"Neg\",\n"
                   "            \"child\": {\n"
                   "              \"type\": \"PangoLineage\",\n"
                   "              \"column\": \"pango_lineage\",\n"
                   "              \"includeSubLineages\": true,\n"
                   "              \"value\": \"B.1.1.529\"\n"
                   "            }\n"
                   "          },\n"
                   "          {\n"
                   "            \"type\": \"N-Of\",\n"
                   "            \"n\": 2,\n"
                   "            \"exactly\": false,\n"
                   "            \"children\": [\n"
                   "              {\n"
                   "                \"type\": \"NucEq\",\n"
                   "                \"position\": 241,\n"
                   "                \"value\": \"T\"\n"
                   "              },\n"
                   "              {\n"
                   "                \"type\": \"NucEq\",\n"
                   "                \"position\": 29734,\n"
                   "                \"value\": \"T\"\n"
                   "              },\n"
                   "              {\n"
                   "                \"type\": \"NucEq\",\n"
                   "                \"position\": 28330,\n"
                   "                \"value\": \"G\"\n"
                   "              }\n"
                   "            ]\n"
                   "          }\n"
                   "        ]\n"
                   "      }\n"
                   "    ]\n"
                   "  }";
