message(STATUS "Conan: Using CMakeDeps conandeps_legacy.cmake aggregator via include()")
message(STATUS "Conan: It is recommended to use explicit find_package() per dependency instead")

find_package(Arrow)
find_package(Boost)
find_package(FastFloat)
find_package(GTest)
find_package(mimalloc)
find_package(nlohmann_json)
find_package(Poco)
find_package(re2)
find_package(roaring)
find_package(simdjson)
find_package(simdutf)
find_package(spdlog)
find_package(yaml-cpp)
find_package(zstd)

set(CONANDEPS_LEGACY  arrow::arrow  boost::boost  FastFloat::fast_float  gtest::gtest  mimalloc-static  nlohmann_json::nlohmann_json  Poco::Poco  re2::re2  roaring::roaring  simdjson::simdjson  simdutf::simdutf  spdlog::spdlog  yaml-cpp::yaml-cpp  zstd::libzstd_static )