ARG DEPENDENCY_IMAGE=ghcr.io/genspectrum/lapis-silo-linter-dependencies:latest

FROM $DEPENDENCY_IMAGE AS linter
ARG THREADS=16

WORKDIR /src

COPY . ./

RUN conan install . --build=missing --profile ./conanprofile --profile:build ./conanprofile --output-folder=build -s build_type=Debug
RUN cmake -D BUILD_WITH_CLANG_TIDY=ON -D CMAKE_BUILD_TYPE=Debug . -B build
RUN cmake --build build --parallel $THREADS
