FROM ubuntu:22.04

ARG TARGETPLATFORM

RUN apt update && apt dist-upgrade -y \
    && apt install -y \
    cmake python3-pip

RUN pip install conan==2.8.1

RUN apt install -y software-properties-common wget gnupg lsb-release wget jq curl \
    && wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc \
    && add-apt-repository 'deb http://apt.llvm.org/jammy/  llvm-toolchain-jammy main' \
    && apt install -y clang-tidy-15

WORKDIR /src
COPY conanfile.py conanprofile.docker conanprofile.docker_arm ./
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
        mv conanprofile.docker_arm conanprofile; \
    else \
        mv conanprofile.docker conanprofile; \
    fi

RUN conan install . --build=missing --profile ./conanprofile --profile:build ./conanprofile --output-folder=build/Release/generators
RUN conan install . --build=missing --profile ./conanprofile --profile:build ./conanprofile --settings "&:build_type=Debug" --output-folder=build/Debug/generators
