FROM ubuntu:22.04

ARG TARGETPLATFORM

RUN apt update \
    && apt install -y \
    cmake=3.22.1-1ubuntu1.22.04.2 \
    python3-pip=22.0.2+dfsg-1ubuntu0.4 \
    software-properties-common=0.99.22.9 \
    wget=1.21.2-2ubuntu1 \
    gnupg=2.2.27-3ubuntu2.1 \
    lsb-release=11.1.0ubuntu4

RUN pip install conan==2.4.1 --break-system-packages

WORKDIR /src
COPY conanfile.py conanprofile.docker conanprofile.docker_arm ./
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
        mv conanprofile.docker_arm conanprofile; \
    else \
        mv conanprofile.docker conanprofile; \
    fi

RUN conan install . --build=missing --profile ./conanprofile --profile:build ./conanprofile --output-folder=build
