version: "3.9"
services:
  silo:
    image: ${SILO_IMAGE}
    volumes:
      - ./testBaseData/exampleDatasetAsNdjson:/preprocessing/input
      - ./testBaseData/output:/preprocessing/output
      - ./testBaseData/exampleDatasetAsNdjson/preprocessing_config.yaml:/app/preprocessing_config.yaml
      - ./testBaseData/exampleDatasetAsNdjson/database_config.yaml:/app/database_config.yaml
      - ./logs:/app/logs
    command:
      - "--preprocessing"
