FROM ubuntu:24.04

ARG TARGETPLATFORM

WORKDIR /src

RUN apt-get update \
    && apt-get install -y \
    cmake \
    build-essential \
    gcc \
    g++ \
    software-properties-common \
    wget \
    gnupg \
    lsb-release \
    pipx \
    && wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc \
    && add-apt-repository 'deb http://apt.llvm.org/mantic/  llvm-toolchain-mantic main' \
    && apt-get update \
    && apt-get install -y clang-tidy-19 \
    && apt-get clean \
    && apt-get autoremove --purge -y

ENV PATH="/root/.local/bin:$PATH"
RUN pipx install conan --pip-args="--no-cache-dir" --system-site-packages

COPY conanfile.py conanprofile.docker conanprofile.docker_arm ./

COPY conanfile.py conanprofile.docker ./
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
        mv conanprofile.docker_arm conanprofile; \
    else \
        mv conanprofile.docker conanprofile; \
    fi

RUN conan install . --build=missing --profile ./conanprofile --profile:build ./conanprofile --output-folder=build -s build_type=Debug
