FROM debian:oldstable

ARG TARGETPLATFORM

RUN apt-get update && apt-get dist-upgrade -y \
    && apt-get install -y \
    build-essential cmake python3 python3-pip python3-venv pipx software-properties-common wget gnupg lsb-release jq curl patchelf clang-tidy-19 nodejs npm

# ensurepath adds a line to .profile
# which puts the pipx install directory ~/.local/bin into the PATH variable
RUN python3 -m pipx ensurepath
# .profile is only sourced on relogin. Dockerfile shells do not login by default.
# This line tells it to execute all subsequent commands with a prior login
SHELL ["/bin/bash", "--login", "-c"]

RUN python3 -m pipx install conan==2.16.1
RUN python3 -m pipx install uv==0.10.2

WORKDIR /src
COPY conanfile.py conanprofile.docker conanprofile.docker_arm ./
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
        mv conanprofile.docker_arm conanprofile; \
    else \
        mv conanprofile.docker conanprofile; \
    fi

RUN conan install . --build=missing --profile ./conanprofile --profile:build ./conanprofile --output-folder=build/Release/generators
RUN conan install . --build=missing --profile ./conanprofile --profile:build ./conanprofile --settings "&:build_type=Debug" --output-folder=build/Debug/generators
