FROM ubuntu:22.04 AS linter

WORKDIR /src

RUN apt update \
    && apt install -y \
    cmake=3.22.1-1ubuntu1.22.04.1 \
    python3-pip=22.0.2+dfsg-1ubuntu0.3 \
    software-properties-common=0.99.22.7 \
    wget=1.21.2-2ubuntu1 \
    gnupg=2.2.27-3ubuntu2.1 \
    lsb-release=11.1.0ubuntu4 \
    && wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc \
    && add-apt-repository 'deb http://apt.llvm.org/jammy/  llvm-toolchain-jammy main' \
    && apt install -y clang-tidy

RUN pip install conan==2.0.8

COPY conanfile.py conanprofile.docker ./
RUN mv conanprofile.docker conanprofile

RUN --mount=type=cache,target=/root/.conan2 \
    conan install . --build=missing --profile ./conanprofile --profile:build ./conanprofile --output-folder=build -s build_type=Debug \
    && cp -R /root/.conan2 /root/.conan2_persisted && cp -R build build_persisted

# Restore the cached directories as the cache mount deletes them.
# We need this because cache mounts are not cached in GitHub Actions
# (see https://github.com/docker/build-push-action/issues/716)
RUN cp -R /root/.conan2_persisted /root/.conan2 && cp -R build_persisted build

COPY . ./

RUN python3 ./build_with_conan.py --parallel 4
