ARG DEPENDENCY_IMAGE=ghcr.io/genspectrum/lapis-silo-linter-dependencies:latest

FROM $DEPENDENCY_IMAGE AS linter
ARG THREADS=16

WORKDIR /app

RUN mv /src/build .

RUN ls -la

COPY ./ .

RUN ls -la

RUN ls -la build

RUN cmake -D BUILD_WITH_CLANG_TIDY=on -D CMAKE_BUILD_TYPE=Debug -B build

RUN cmake --build build --parallel $THREADS
