version: "3.9"
services:
  silo:
    image: ${SILO_IMAGE}
    volumes:
      - ./testBaseData:/data
    ports:
      - "8080:8081"
    command:
      - "--api"
      - "--preprocessingConfig=./preprocessing_config_for_ci.yaml"
      - "--databaseConfig=./test_database_config.yaml"

