FROM ubuntu:22.04

WORKDIR /src

RUN apt update \
    && apt install -y \
    cmake \
    python3-pip \
    software-properties-common \
    wget \
    gnupg \
    lsb-release \
    && wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc \
    && add-apt-repository 'deb http://apt.llvm.org/jammy/  llvm-toolchain-jammy main' \
    && apt install -y clang-tidy-20 \
    && apt install -y jq \
    && apt install -y curl

RUN pip install conan==2.0.17

RUN cat <<EOF > conanprofile
[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=9.3
build_type=Debug
[options]
EOF

COPY conanfile.py ./


RUN conan install . --build=missing --profile ./conanprofile --profile:build ./conanprofile --output-folder=build -s build_type=Debug

