version: "3.9"
services:
  silo:
    image: ${SILO_IMAGE}
    volumes:
      - ./testBaseData:/app/testBaseData
    ports:
      - "8080:8081"
    command:
      - "--api"
      - "--preprocessingConfig=./testBaseData/test_preprocessing_config.yaml"
      - "--databaseConfig=./testBaseData/test_database_config.yaml"

