########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

list(APPEND pcre2_COMPONENT_NAMES PCRE2::8BIT PCRE2::16BIT PCRE2::32BIT PCRE2::POSIX)
list(REMOVE_DUPLICATES pcre2_COMPONENT_NAMES)
if(DEFINED pcre2_FIND_DEPENDENCY_NAMES)
  list(APPEND pcre2_FIND_DEPENDENCY_NAMES BZip2 ZLIB)
  list(REMOVE_DUPLICATES pcre2_FIND_DEPENDENCY_NAMES)
else()
  set(pcre2_FIND_DEPENDENCY_NAMES BZip2 ZLIB)
endif()
set(BZip2_FIND_MODE "MODULE")
set(ZLIB_FIND_MODE "MODULE")

########### VARIABLES #######################################################################
#############################################################################################
set(pcre2_PACKAGE_FOLDER_RELEASE "/root/.conan2/p/b/pcre2837df0f5f22ea/p")
set(pcre2_BUILD_MODULES_PATHS_RELEASE )


set(pcre2_INCLUDE_DIRS_RELEASE )
set(pcre2_RES_DIRS_RELEASE )
set(pcre2_DEFINITIONS_RELEASE "-DPCRE2_STATIC")
set(pcre2_SHARED_LINK_FLAGS_RELEASE )
set(pcre2_EXE_LINK_FLAGS_RELEASE )
set(pcre2_OBJECTS_RELEASE )
set(pcre2_COMPILE_DEFINITIONS_RELEASE "PCRE2_STATIC")
set(pcre2_COMPILE_OPTIONS_C_RELEASE )
set(pcre2_COMPILE_OPTIONS_CXX_RELEASE )
set(pcre2_LIB_DIRS_RELEASE "${pcre2_PACKAGE_FOLDER_RELEASE}/lib")
set(pcre2_BIN_DIRS_RELEASE )
set(pcre2_LIBRARY_TYPE_RELEASE STATIC)
set(pcre2_IS_HOST_WINDOWS_RELEASE 0)
set(pcre2_LIBS_RELEASE pcre2-posix pcre2-32 pcre2-16 pcre2-8)
set(pcre2_SYSTEM_LIBS_RELEASE )
set(pcre2_FRAMEWORK_DIRS_RELEASE )
set(pcre2_FRAMEWORKS_RELEASE )
set(pcre2_BUILD_DIRS_RELEASE )
set(pcre2_NO_SONAME_MODE_RELEASE FALSE)


# COMPOUND VARIABLES
set(pcre2_COMPILE_OPTIONS_RELEASE
    "$<$<COMPILE_LANGUAGE:CXX>:${pcre2_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${pcre2_COMPILE_OPTIONS_C_RELEASE}>")
set(pcre2_LINKER_FLAGS_RELEASE
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pcre2_SHARED_LINK_FLAGS_RELEASE}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pcre2_SHARED_LINK_FLAGS_RELEASE}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pcre2_EXE_LINK_FLAGS_RELEASE}>")


set(pcre2_COMPONENTS_RELEASE PCRE2::8BIT PCRE2::16BIT PCRE2::32BIT PCRE2::POSIX)
########### COMPONENT PCRE2::POSIX VARIABLES ############################################

set(pcre2_PCRE2_POSIX_INCLUDE_DIRS_RELEASE )
set(pcre2_PCRE2_POSIX_LIB_DIRS_RELEASE "${pcre2_PACKAGE_FOLDER_RELEASE}/lib")
set(pcre2_PCRE2_POSIX_BIN_DIRS_RELEASE )
set(pcre2_PCRE2_POSIX_LIBRARY_TYPE_RELEASE STATIC)
set(pcre2_PCRE2_POSIX_IS_HOST_WINDOWS_RELEASE 0)
set(pcre2_PCRE2_POSIX_RES_DIRS_RELEASE )
set(pcre2_PCRE2_POSIX_DEFINITIONS_RELEASE )
set(pcre2_PCRE2_POSIX_OBJECTS_RELEASE )
set(pcre2_PCRE2_POSIX_COMPILE_DEFINITIONS_RELEASE )
set(pcre2_PCRE2_POSIX_COMPILE_OPTIONS_C_RELEASE "")
set(pcre2_PCRE2_POSIX_COMPILE_OPTIONS_CXX_RELEASE "")
set(pcre2_PCRE2_POSIX_LIBS_RELEASE pcre2-posix)
set(pcre2_PCRE2_POSIX_SYSTEM_LIBS_RELEASE )
set(pcre2_PCRE2_POSIX_FRAMEWORK_DIRS_RELEASE )
set(pcre2_PCRE2_POSIX_FRAMEWORKS_RELEASE )
set(pcre2_PCRE2_POSIX_DEPENDENCIES_RELEASE PCRE2::8BIT)
set(pcre2_PCRE2_POSIX_SHARED_LINK_FLAGS_RELEASE )
set(pcre2_PCRE2_POSIX_EXE_LINK_FLAGS_RELEASE )
set(pcre2_PCRE2_POSIX_NO_SONAME_MODE_RELEASE FALSE)

# COMPOUND VARIABLES
set(pcre2_PCRE2_POSIX_LINKER_FLAGS_RELEASE
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pcre2_PCRE2_POSIX_SHARED_LINK_FLAGS_RELEASE}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pcre2_PCRE2_POSIX_SHARED_LINK_FLAGS_RELEASE}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pcre2_PCRE2_POSIX_EXE_LINK_FLAGS_RELEASE}>
)
set(pcre2_PCRE2_POSIX_COMPILE_OPTIONS_RELEASE
    "$<$<COMPILE_LANGUAGE:CXX>:${pcre2_PCRE2_POSIX_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${pcre2_PCRE2_POSIX_COMPILE_OPTIONS_C_RELEASE}>")
########### COMPONENT PCRE2::32BIT VARIABLES ############################################

set(pcre2_PCRE2_32BIT_INCLUDE_DIRS_RELEASE )
set(pcre2_PCRE2_32BIT_LIB_DIRS_RELEASE "${pcre2_PACKAGE_FOLDER_RELEASE}/lib")
set(pcre2_PCRE2_32BIT_BIN_DIRS_RELEASE )
set(pcre2_PCRE2_32BIT_LIBRARY_TYPE_RELEASE STATIC)
set(pcre2_PCRE2_32BIT_IS_HOST_WINDOWS_RELEASE 0)
set(pcre2_PCRE2_32BIT_RES_DIRS_RELEASE )
set(pcre2_PCRE2_32BIT_DEFINITIONS_RELEASE "-DPCRE2_STATIC")
set(pcre2_PCRE2_32BIT_OBJECTS_RELEASE )
set(pcre2_PCRE2_32BIT_COMPILE_DEFINITIONS_RELEASE "PCRE2_STATIC")
set(pcre2_PCRE2_32BIT_COMPILE_OPTIONS_C_RELEASE "")
set(pcre2_PCRE2_32BIT_COMPILE_OPTIONS_CXX_RELEASE "")
set(pcre2_PCRE2_32BIT_LIBS_RELEASE pcre2-32)
set(pcre2_PCRE2_32BIT_SYSTEM_LIBS_RELEASE )
set(pcre2_PCRE2_32BIT_FRAMEWORK_DIRS_RELEASE )
set(pcre2_PCRE2_32BIT_FRAMEWORKS_RELEASE )
set(pcre2_PCRE2_32BIT_DEPENDENCIES_RELEASE )
set(pcre2_PCRE2_32BIT_SHARED_LINK_FLAGS_RELEASE )
set(pcre2_PCRE2_32BIT_EXE_LINK_FLAGS_RELEASE )
set(pcre2_PCRE2_32BIT_NO_SONAME_MODE_RELEASE FALSE)

# COMPOUND VARIABLES
set(pcre2_PCRE2_32BIT_LINKER_FLAGS_RELEASE
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pcre2_PCRE2_32BIT_SHARED_LINK_FLAGS_RELEASE}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pcre2_PCRE2_32BIT_SHARED_LINK_FLAGS_RELEASE}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pcre2_PCRE2_32BIT_EXE_LINK_FLAGS_RELEASE}>
)
set(pcre2_PCRE2_32BIT_COMPILE_OPTIONS_RELEASE
    "$<$<COMPILE_LANGUAGE:CXX>:${pcre2_PCRE2_32BIT_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${pcre2_PCRE2_32BIT_COMPILE_OPTIONS_C_RELEASE}>")
########### COMPONENT PCRE2::16BIT VARIABLES ############################################

set(pcre2_PCRE2_16BIT_INCLUDE_DIRS_RELEASE )
set(pcre2_PCRE2_16BIT_LIB_DIRS_RELEASE "${pcre2_PACKAGE_FOLDER_RELEASE}/lib")
set(pcre2_PCRE2_16BIT_BIN_DIRS_RELEASE )
set(pcre2_PCRE2_16BIT_LIBRARY_TYPE_RELEASE STATIC)
set(pcre2_PCRE2_16BIT_IS_HOST_WINDOWS_RELEASE 0)
set(pcre2_PCRE2_16BIT_RES_DIRS_RELEASE )
set(pcre2_PCRE2_16BIT_DEFINITIONS_RELEASE "-DPCRE2_STATIC")
set(pcre2_PCRE2_16BIT_OBJECTS_RELEASE )
set(pcre2_PCRE2_16BIT_COMPILE_DEFINITIONS_RELEASE "PCRE2_STATIC")
set(pcre2_PCRE2_16BIT_COMPILE_OPTIONS_C_RELEASE "")
set(pcre2_PCRE2_16BIT_COMPILE_OPTIONS_CXX_RELEASE "")
set(pcre2_PCRE2_16BIT_LIBS_RELEASE pcre2-16)
set(pcre2_PCRE2_16BIT_SYSTEM_LIBS_RELEASE )
set(pcre2_PCRE2_16BIT_FRAMEWORK_DIRS_RELEASE )
set(pcre2_PCRE2_16BIT_FRAMEWORKS_RELEASE )
set(pcre2_PCRE2_16BIT_DEPENDENCIES_RELEASE )
set(pcre2_PCRE2_16BIT_SHARED_LINK_FLAGS_RELEASE )
set(pcre2_PCRE2_16BIT_EXE_LINK_FLAGS_RELEASE )
set(pcre2_PCRE2_16BIT_NO_SONAME_MODE_RELEASE FALSE)

# COMPOUND VARIABLES
set(pcre2_PCRE2_16BIT_LINKER_FLAGS_RELEASE
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pcre2_PCRE2_16BIT_SHARED_LINK_FLAGS_RELEASE}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pcre2_PCRE2_16BIT_SHARED_LINK_FLAGS_RELEASE}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pcre2_PCRE2_16BIT_EXE_LINK_FLAGS_RELEASE}>
)
set(pcre2_PCRE2_16BIT_COMPILE_OPTIONS_RELEASE
    "$<$<COMPILE_LANGUAGE:CXX>:${pcre2_PCRE2_16BIT_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${pcre2_PCRE2_16BIT_COMPILE_OPTIONS_C_RELEASE}>")
########### COMPONENT PCRE2::8BIT VARIABLES ############################################

set(pcre2_PCRE2_8BIT_INCLUDE_DIRS_RELEASE )
set(pcre2_PCRE2_8BIT_LIB_DIRS_RELEASE "${pcre2_PACKAGE_FOLDER_RELEASE}/lib")
set(pcre2_PCRE2_8BIT_BIN_DIRS_RELEASE )
set(pcre2_PCRE2_8BIT_LIBRARY_TYPE_RELEASE STATIC)
set(pcre2_PCRE2_8BIT_IS_HOST_WINDOWS_RELEASE 0)
set(pcre2_PCRE2_8BIT_RES_DIRS_RELEASE )
set(pcre2_PCRE2_8BIT_DEFINITIONS_RELEASE "-DPCRE2_STATIC")
set(pcre2_PCRE2_8BIT_OBJECTS_RELEASE )
set(pcre2_PCRE2_8BIT_COMPILE_DEFINITIONS_RELEASE "PCRE2_STATIC")
set(pcre2_PCRE2_8BIT_COMPILE_OPTIONS_C_RELEASE "")
set(pcre2_PCRE2_8BIT_COMPILE_OPTIONS_CXX_RELEASE "")
set(pcre2_PCRE2_8BIT_LIBS_RELEASE pcre2-8)
set(pcre2_PCRE2_8BIT_SYSTEM_LIBS_RELEASE )
set(pcre2_PCRE2_8BIT_FRAMEWORK_DIRS_RELEASE )
set(pcre2_PCRE2_8BIT_FRAMEWORKS_RELEASE )
set(pcre2_PCRE2_8BIT_DEPENDENCIES_RELEASE ZLIB::ZLIB BZip2::BZip2)
set(pcre2_PCRE2_8BIT_SHARED_LINK_FLAGS_RELEASE )
set(pcre2_PCRE2_8BIT_EXE_LINK_FLAGS_RELEASE )
set(pcre2_PCRE2_8BIT_NO_SONAME_MODE_RELEASE FALSE)

# COMPOUND VARIABLES
set(pcre2_PCRE2_8BIT_LINKER_FLAGS_RELEASE
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pcre2_PCRE2_8BIT_SHARED_LINK_FLAGS_RELEASE}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pcre2_PCRE2_8BIT_SHARED_LINK_FLAGS_RELEASE}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pcre2_PCRE2_8BIT_EXE_LINK_FLAGS_RELEASE}>
)
set(pcre2_PCRE2_8BIT_COMPILE_OPTIONS_RELEASE
    "$<$<COMPILE_LANGUAGE:CXX>:${pcre2_PCRE2_8BIT_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${pcre2_PCRE2_8BIT_COMPILE_OPTIONS_C_RELEASE}>")