#pragma once

//! Part of config metadata, but can't be in `config_metadata.h` due to
//! that depending on `config/config_source_interface.h` which also
//! references `ConfigValue`.

#include <optional>
#include <span>
#include <variant>

// Using `const char*` for string literals; this makes those easier to
// use (std::string_view isn't compatible to the same level).

class ConfigValue {
  public:
   /// Human readable or autogenerated?
   const char* type_name;
   /// In the unparsed form as given by user in env vars or command
   /// line args.
   std::optional<const char*> default_value;
   /// Help as shown for --help, excluding the other info above.
   const char* help_text;

   /// If true, the command line option does not take an argument but
   /// is the constant "true".
   [[nodiscard]] bool isBool() const;
};
