schema:
  instanceName: empty_input_in_ndjson_format_without_partitioning
  metadata:
    - name: primaryKey
      type: string
    - name: date
      type: date
    - name: region
      type: string
      generateIndex: true
    - name: pango_lineage
      type: string
      generateIndex: true
      lineageIndex: true
    - name: division
      type: string
      generateIndex: true
    - name: age
      type: int
    - name: qc_value
      type: float
  primaryKey: primaryKey
