schema:
  instanceName: "RSV A"
  opennessLevel: OPEN
  metadata:
    - name: accession
      type: string
    - name: version
      type: int
    - name: submissionId
      type: string
    - name: accessionVersion
      type: string
    - name: isRevocation
      type: boolean
    - name: submitter
      type: string
      generateIndex: true
    - name: groupId
      type: int
    - name: groupName
      type: string
      generateIndex: true
    - name: submittedAt
      type: int
    - name: releasedAt
      type: int
    - name: dataUseTerms
      type: string
      generateIndex: true
    - name: dataUseTermsRestrictedUntil
      type: date
    - name: versionStatus
      type: string
    - name: sample_collection_date
      type: date
    - name: ncbi_release_date
      type: date
    - name: ncbi_update_date
      type: date
    - name: geo_loc_country
      type: string
      generateIndex: true
    - name: geo_loc_admin_1
      type: string
      generateIndex: true
    - name: geo_loc_admin_2
      type: string
      generateIndex: true
    - name: geo_loc_city
      type: string
      generateIndex: true
    - name: geo_loc_site
      type: string
    - name: specimen_collector_sample_id
      type: string
    - name: authors
      type: string
    - name: author_affiliations
      type: string
      generateIndex: true
    - name: ncbi_submitter_country
      type: string
      generateIndex: true
    - name: insdc_accession_base
      type: string
    - name: insdc_version
      type: int
    - name: insdc_accession_full
      type: string
    - name: bioproject_accessions
      type: string
    - name: biosample_accession
      type: string
    - name: culture_id
      type: string
    - name: sample_received_date
      type: date
    - name: sample_type
      type: string
    - name: purpose_of_sampling
      type: string
    - name: presampling_activity
      type: string
    - name: anatomical_material
      type: string
    - name: anatomical_part
      type: string
    - name: body_product
      type: string
    - name: environmental_material
      type: string
    - name: environmental_site
      type: string
    - name: collection_device
      type: string
    - name: collection_method
      type: string
    - name: food_product
      type: string
    - name: food_product_properties
      type: string
    - name: specimen_processing
      type: string
    - name: specimen_processing_details
      type: string
    - name: experimental_specimen_role_type
      type: string
    - name: host_age
      type: int
    - name: host_age_bin
      type: string
    - name: host_gender
      type: string
    - name: host_origin_country
      type: string
    - name: host_disease
      type: string
    - name: signs_and_symptoms
      type: string
    - name: host_health_state
      type: string
    - name: host_health_outcome
      type: string
    - name: travel_history
      type: string
    - name: exposure_event
      type: string
    - name: host_role
      type: string
    - name: exposure_setting
      type: string
    - name: exposure_details
      type: string
    - name: previous_infection_disease
      type: string
    - name: previous_infection_organism
      type: string
    - name: host_vaccination_status
      type: string
    - name: purpose_of_sequencing
      type: string
    - name: sequencing_date
      type: date
    - name: amplicon_pcr_primer_scheme
      type: string
    - name: amplicon_size
      type: string
    - name: sequencing_instrument
      type: string
    - name: sequencing_protocol
      type: string
    - name: sequencing_assay_type
      type: string
    - name: sequenced_by_organization
      type: string
    - name: sequenced_by_contact_name
      type: string
    - name: sequenced_by_contact_email
      type: string
    - name: raw_sequence_data_processing_method
      type: string
    - name: dehosting_method
      type: string
    - name: reference_genome_accession
      type: string
    - name: consensus_sequence_software_name
      type: string
    - name: consensus_sequence_software_version
      type: string
    - name: depth_of_coverage
      type: int
    - name: breadth_of_coverage
      type: int
    - name: quality_control_method_name
      type: string
    - name: quality_control_method_version
      type: string
    - name: quality_control_determination
      type: string
    - name: quality_control_issues
      type: string
    - name: quality_control_details
      type: string
    - name: diagnostic_measurement_method
      type: string
    - name: diagnostic_target_presence
      type: string
    - name: diagnostic_target_gene_name
      type: string
    - name: diagnostic_measurement_value
      type: string
    - name: diagnostic_measurement_unit
      type: string
    - name: ncbi_completeness
      type: string
      generateIndex: true
    - name: length
      type: int
    - name: host_name_scientific
      type: string
      generateIndex: true
    - name: host_name_common
      type: string
      generateIndex: true
    - name: host_taxon_id
      type: int
    - name: is_lab_host
      type: string
      generateIndex: true
    - name: cell_line
      type: string
      generateIndex: true
    - name: passage_number
      type: int
    - name: passage_method
      type: string
      generateIndex: true
    - name: ncbi_protein_count
      type: int
    - name: ncbi_sourcedb
      type: string
      generateIndex: true
    - name: ncbi_virus_name
      type: string
      generateIndex: true
    - name: ncbi_virus_tax_id
      type: int
    - name: sra_run_accession
      type: string
    - name: total_snps
      type: int
    - name: lineage
      type: string
      generateIndex: true
    - name: total_inserted_nucs
      type: int
    - name: total_deleted_nucs
      type: int
    - name: total_ambiguous_nucs
      type: int
    - name: total_unknown_nucs
      type: int
    - name: total_frame_shifts
      type: int
    - name: frame_shifts
      type: string
    - name: completeness
      type: float
    - name: total_stop_codons
      type: int
    - name: stop_codons
      type: string
  primaryKey: insdc_accession_full
  dateToSortBy: sample_collection_date
