services:
  lapisOpen:
    image: ghcr.io/genspectrum/lapis:${LAPIS_TAG}
    ports:
      - "8090:8080"
    command: --silo.url=http://silo:8081
    volumes:
      - type: bind
        source: ./database_config.yaml
        target: /workspace/database_config.yaml
      - type: bind
        source: ./reference_genomes.json
        target: /workspace/reference_genomes.json

  silo:
    image: ghcr.io/genspectrum/lapis-silo:${SILO_TAG}
    ports:
      - "8091:8081"
    command: api
    volumes:
      - ./output:/data
    depends_on:
      siloPreprocessing:
        condition: service_completed_successfully

  siloPreprocessing:
    image: ghcr.io/genspectrum/lapis-silo:${SILO_TAG}
    command: preprocessing
    volumes:
      - ./:/preprocessing/input
      - ./output:/preprocessing/output
      - ./preprocessing_config.yaml:/app/preprocessing_config.yaml

