inputDirectory: "./testBaseData/unitTestDummyDataset/"
outputDirectory: "./output/"
metadataFilename: "metadata.tsv"
pangoLineageDefinitionFilename: "pangolineage_alias.json"
referenceGenomeFilename: "reference_genomes.json"
