inputDirectory: "./testBaseData/unitTestDummyDataset/"
outputDirectory: "./output/"
ndjsonInputFilename: "input.ndjson"
lineageDefinitionFilenames:
  - "test_lineage_definition.yaml"
phyloTreeFilename: "phylogenetic_tree.nwk"
referenceGenomeFilename: "reference_genomes.json"
