inputDirectory: "./testBaseData/unitTestDummyDataset/"
outputDirectory: "./output/"
ndjsonInputFilename: "input.ndjson"
lineageDefinitionsFilename: "lineage_definitions.yaml"
phyloTreeFilename: "phylogenetic_tree.nwk"
referenceGenomeFilename: "reference_genomes.json"
