inputDirectory: "./testBaseData/unitTestDummyDataset/"
outputDirectory: "./output/"
metadataFilename: "metadata.tsv"
lineageDefinitionsFilename: "lineage_definitions.yaml"
referenceGenomeFilename: "reference_genomes.json"
