#include "silo/common/nucleotide_symbols.h"
#include "silo/common/panic.h"

namespace silo {

const silo::SymbolMap<Nucleotide, std::vector<Nucleotide::Symbol>> Nucleotide::AMBIGUITY_SYMBOLS{{{
   {Nucleotide::Symbol::GAP},
   {Nucleotide::Symbol::A,
    Nucleotide::Symbol::R,
    Nucleotide::Symbol::M,
    Nucleotide::Symbol::W,
    Nucleotide::Symbol::D,
    Nucleotide::Symbol::H,
    Nucleotide::Symbol::V,
    Nucleotide::Symbol::N},
   {Nucleotide::Symbol::C,
    Nucleotide::Symbol::Y,
    Nucleotide::Symbol::M,
    Nucleotide::Symbol::S,
    Nucleotide::Symbol::B,
    Nucleotide::Symbol::H,
    Nucleotide::Symbol::V,
    Nucleotide::Symbol::N},
   {Nucleotide::Symbol::G,
    Nucleotide::Symbol::R,
    Nucleotide::Symbol::K,
    Nucleotide::Symbol::S,
    Nucleotide::Symbol::B,
    Nucleotide::Symbol::D,
    Nucleotide::Symbol::V,
    Nucleotide::Symbol::N},
   {Nucleotide::Symbol::T,
    Nucleotide::Symbol::Y,
    Nucleotide::Symbol::K,
    Nucleotide::Symbol::W,
    Nucleotide::Symbol::B,
    Nucleotide::Symbol::D,
    Nucleotide::Symbol::H,
    Nucleotide::Symbol::N},
   {Nucleotide::Symbol::R},
   {Nucleotide::Symbol::Y},
   {Nucleotide::Symbol::S},
   {Nucleotide::Symbol::W},
   {Nucleotide::Symbol::K},
   {Nucleotide::Symbol::M},
   {Nucleotide::Symbol::B},
   {Nucleotide::Symbol::D},
   {Nucleotide::Symbol::H},
   {Nucleotide::Symbol::V},
   {Nucleotide::Symbol::N},
}}};
}  // namespace silo
