schema:
  instanceName: empty_input_in_ndjson_format
  metadata:
    - name: gisaid_epi_isl
      type: string
    - name: date
      type: date
    - name: region
      type: string
      generateIndex: true
    - name: pango_lineage
      type: string
      generateIndex: true
      lineageIndex: true
    - name: division
      type: string
      generateIndex: true
    - name: age
      type: int
    - name: qc_value
      type: float
  primaryKey: gisaid_epi_isl
  dateToSortBy: date
  partitionBy: pango_lineage
