schema:
  instanceName: RSV A
  opennessLevel: OPEN
  metadata:
    - name: accessionVersion
      type: string
    - name: sample_collection_date
      type: date
  primaryKey: accessionVersion
  dateToSortBy: sample_collection_date
