#!/bin/bash

set -euo pipefail

DOCKER_IMAGE="${1:-ghcr.io/genspectrum/lapis-silo-dependencies:latest}"

echo "Using Docker image: $DOCKER_IMAGE"

DOCKER_BUILD_CACHE_VOLUME="${LINT_DOCKER_BUILD_CACHE_VOLUME:-DockerBuildCache-$(basename "$(pwd)" | tr -c 'A-Za-z0-9_.-' '_2')}"
echo "Using Docker volume for build cache: $DOCKER_BUILD_CACHE_VOLUME (clear with: docker volume rm \"$DOCKER_BUILD_CACHE_VOLUME\")"

docker run --rm \
  -v "$(pwd)/.clang-tidy:/src/.clang-tidy" \
  -v "$(pwd)/performance:/src/performance" \
  -v "$(pwd)/src:/src/src" \
  -v "$(pwd)/CMakeLists.txt:/src/CMakeLists.txt" \
  -v "${DOCKER_BUILD_CACHE_VOLUME}:/src/build/Debug" \
  "$DOCKER_IMAGE" \
  /bin/bash --login -c '
    set -euo pipefail
    cmake -G Ninja -D BUILD_WITH_CLANG_TIDY=ON -D CMAKE_BUILD_TYPE=Debug -B build/Debug
    cmake --build build/Debug --target silo -- -k 0'
