
set(
        INCLUDE_H
        include/silo/common/FixHashtable.hpp
        include/silo/common/hashing.h
        include/silo/common/PerfEvent.hpp
        include/silo/common/SizeSketch.h
        include/silo/common/Vec8U.h
        include/silo/common/silo_symbols.h
        include/silo/common/istream_wrapper.h
        include/silo/common/lehmer64.h
        include/silo/common/splitmix64.h
        include/silo/storage/Dictionary.h
        include/silo/storage/meta_store.h
        include/silo/storage/sequence_store.h
        include/silo/roaring/roaring.hh
        include/silo/roaring/roaring.h
        include/silo/roaring/roaring_serialize.h
        include/silo/query_engine/query_engine.h
        include/silo/prepare_dataset.h
        include/silo/database.h
        include/silo/benchmark.h
        include/silo/bootstrap.h
)
