inputDirectory: "./testBaseData/exampleDataset/"
outputDirectory: "./output/custom/"
intermediateResultsDirectory: "./output/overriddenTemp/"
metadataFilename: "small_metadata_set.tsv"
pangoLineageDefinitionFilename: "pangolineage_alias.json"
referenceGenomeFilename: "reference_genomes.json"
genePrefix: "aaSeq_"
nucleotideSequencePrefix: ""