inputDirectory: "./testBaseData/exampleDatasetAsTsv/"
outputDirectory: "./output/custom/"
intermediateResultsDirectory: "./output/overriddenTemp/"
metadataFilename: "small_metadata_set.tsv"
lineageDefinitionsFilename: "lineage_definitions.yaml"
referenceGenomeFilename: "reference_genomes.json"
genePrefix: "aaSeq_"
nucleotideSequencePrefix: ""