schema:
  instanceName: sars_cov-2_minimal_test_config
  metadata:
    - name: gisaid_epi_isl
      type: string
    - name: date
      type: date
    - name: unsorted_date
      type: date
    - name: region
      type: string
    - name: country
      type: string
    - name: pango_lineage
      type: pango_lineage
    - name: division
      type: string
  primaryKey: gisaid_epi_isl