inputDirectory: "./testBaseData/exampleDatasetAsTsv/"
outputDirectory: "./output/"
metadataFilename: "small_metadata_set.tsv"
lineageDefinitionsFilename: "lineage_definitions.yaml"
referenceGenomeFilename: "reference_genomes.json"
