schema:
  instanceName: sars_cov-2_minimal_test_config
  metadata:
    - name: gisaid_epi_isl
      type: string
      isPhyloTreeField: true
    - name: date
      type: date
    - name: unsorted_date
      type: date
    - name: region
      type: string
      generateIndex: true
    - name: country
      type: string
      generateIndex: true
    - name: pango_lineage
      type: string
      generateIndex: true
      generateLineageIndex: lineage
    - name: division
      type: string
      generateIndex: true
    - name: age
      type: int
    - name: qc_value
      type: float
  primaryKey: gisaid_epi_isl
