inputDirectory: "./testBaseData/"
outputDirectory: "./output/"
metadataFilename: "small_metadata_set.tsv"
sequenceFilename: "small_sequence_set.fasta"
pangoLineageDefinitionFilename: "pango_alias.txt"
referenceGenomeFilename: "reference_genome.txt"
partitionsFolder: "folder1/"
sortedPartitionsFolder: "folder2/"
serializedStateFolder: "folder3/"