inputDirectory: "./testBaseData/exampleDataset/"
outputDirectory: "./output/"
metadataFilename: "small_metadata_set.tsv"
pangoLineageDefinitionFilename: "pangolineage_alias.json"
referenceGenomeFilename: "reference-genomes.json"
partitionsFolder: "folder1/"
sortedPartitionsFolder: "folder2/"
serializedStateFolder: "folder3/"
genePrefix: "aaSeq_"
nucleotideSequencePrefix: ""