inputDirectory: "./testBaseData/exampleDataset/"
outputDirectory: "./output/"
ndjsonInputFilename: "input_file.ndjson"
lineageDefinitionFilenames:
  - "lineage_definition.yaml"
phyloTreeFilename: "phylogenetic_tree.nwk"
referenceGenomeFilename: "reference_genomes.json"
