inputDirectory: "./testBaseData/"
outputDirectory: "./output/"
metadataFilename: "small_metadata_set.tsv"
sequenceFilename: "small_sequence_set.fasta"
pangoLineageDefinitionFilename: "pango_alias.txt"
partitionFolder: "partitioned/"
sortedPartitionFolder: "sorted_partitions/"
serializationFolder: "serialized_state/"
