inputDirectory: "./testBaseData/exampleDataset/"
outputDirectory: "./output/"
ndjsonInputFilename: "input_file.ndjson"
lineageDefinitionsFilename: "lineage_definitions.yaml"
phyloTreeFilename: "phylogenetic_tree.nwk"
referenceGenomeFilename: "reference_genomes.json"
