schema:
  instanceName: sars_cov-2_minimal_test_config
  nucleotideSequences:
    - name: main
  aminoAcidSequences:
    - name: E
    - name: M
    - name: N
    - name: S
    - name: ORF1A
    - name: ORF1B
    - name: ORF3A
    - name: ORF6
    - name: ORF7A
    - name: ORF7B
    - name: ORF8
    - name: ORF9B
  metadata:
    - name: gisaid_epi_isl
      type: string
    - name: date
      type: date
    - name: unsorted_date
      type: date
    - name: region
      type: string
      generateIndex: true
    - name: country
      type: string
      generateIndex: true
    - name: pango_lineage
      type: pango_lineage
    - name: division
      type: string
      generateIndex: true
    - name: age
      type: int
    - name: qc_value
      type: float
  primaryKey: gisaid_epi_isl
  dateToSortBy: date
  partitionBy: pango_lineage