schema:
  instanceName: Test
  metadata:
    - name: date
      type: date
    - name: host
      type: string
    - name: pangoLineage
      type: string
      generateIndex: true
    - name: accessionVersion
      type: string
  primaryKey: accessionVersion
  dateToSortBy: date
