name: Release SILO

on:
  push:
  workflow_run:
    workflows: [LAPIS-SILO]
    types: [completed]
    branches: [346-release-concept]

env:
  DOCKER_IMAGE_NAME: ghcr.io/genspectrum/lapis-silo

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    if: ${{ github.repository == 'GenSpectrum/LAPIS-SILO' }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          path: .
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: 346-release-concept

      - name: Inspect Release Outputs
        run: |
          cat <<'EOF'
          ${{ toJson(steps.release.outputs) }}
          EOF

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up Docker Buildx
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Already Built Images With Release Tags
        if: ${{ steps.release.outputs.release_created }}
        run: |
          MAJOR=${{ steps.release.outputs.major }}
          MINOR=${{ steps.release.outputs.minor }}
          PATCH=${{ steps.release.outputs.patch }}
          TAGS=("$MAJOR.$MINOR" "$MAJOR.$MINOR.$PATCH")
          # TODO (#405) include $MAJOR only for releases >= 1.0
          # TAGS=("$MAJOR" "$MAJOR.$MINOR" "$MAJOR.$MINOR.$PATCH")
          for TAG in "${TAGS[@]}"; do
            docker buildx imagetools create --tag $DOCKER_IMAGE_NAME:$TAG $DOCKER_IMAGE_NAME:latest
          done
