name: Release SILO

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ghcr.io/genspectrum/lapis-silo

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          path: .
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: main

      - name: Inspect Release Outputs
        run: |
          cat <<'EOF'
          ${{ toJson(steps.release.outputs) }}
          EOF

      # The "LAPIS-SILO" workflow should start after this one finishes
